# Generated by Django 4.0.8 on 2024-07-07 20:08

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
